### ISSUE TITLE
Swipe motion on suggestions makes switching between suggesters hard

### ISSUE THREAD

**Issue by BjoernPetersen** [IIIuminator/EnQ#28]
Swiping on suggested songs currently triggers the favorite/remove functions, which makes it almost impossible to swipe between suggester pages.

**Comment by IIIuminator** [comment]
I'm aware of the issue, not sure how to fix it best though. My best idea is to add an delete button and remove the favorite action. I think more than one button will make it look much to crowded.
Other options like double taps or long press are possible but then the controls are too inconsistent between sections.

**Comment by IIIuminator** [comment]
Third option would be a context menu. Also the search should have the same issue with one action less so maybe less present.

**Comment by BjoernPetersen** [comment]
I think it would be a-ok to limit the favorite action to songs in the queue/currently playing.
As for the remove action: a remove button is probably the most obvious way to show the users about that feature, so I'm all for it.

Regarding consistency: I think adding a song from the favorites tab should probably work by tapping it instead of swiping it.
