### ISSUE TITLE
App crash on unknown suggester

### ISSUE THREAD

**Issue by FelixGail** [IIIuminator/EnQ#41]
Songs starred from a suggester that is no longer available crashes the app.

As the goal of starred songs is to remember interesting songs and the app can potentially be used on different bot instances with incompatible providers, the best solution would probably be trying to use the started song, and if no suitable provider is found, the song is simply searched on available providers.

**Comment by IIIuminator** [comment]
will add a redirect to a search on all providers once #42 is implemented
