### ISSUE TITLE
userId for guest users should be recreatable

### ISSUE THREAD

**Issue by BjoernPetersen** [IIIuminator/EnQ#82]
As far as I can tell, the app currently generates a random UUID as the `userId` for guest users. Ideally, the ID should be bound to the device and recreatable, such as the android device ID.

If the `userId` is the android user ID, the user could even delete all app data and still log in with the same username as a guest.

**Comment by IIIuminator** [comment]
using the android id or other hardware identifiers is strongly discouraged but I'll simply switch to using an instance id. That makes it consistent unless you reinstall or wipe the data.
